## This is the configuration file for the CI/CD system, and dictates
## which Ruby versions, variants and distributions we build.

## (Required)
## Ruby package settings.
ruby:
  ## (Optional)
  ## Which minor Ruby version packages to build, and what their latest tiny
  ## version is.
  ##
  ## NOTE: if you change an existing `full_version` value,
  ## then be sure to bump the corresponding `package_revision`!
  minor_version_packages:
    - minor_version: 3.1
      full_version: 3.1.0
      package_revision: 5
    - minor_version: 3.0
      full_version: 3.0.3
      package_revision: 5
    - minor_version: 2.7
      full_version: 2.7.5
      package_revision: 7

  ## (Optional)
  ## Which tiny Ruby version packages to build.
  tiny_version_packages:
    - full_version: 3.1.0
      package_revision: 1
    - full_version: 3.0.3
      package_revision: 5
    - full_version: 2.7.5
      package_revision: 6

## (Required)
## Which Rbenv version to package.
rbenv:
  ## (Required: specify either 'repo' and 'ref', or just 'path')

  ## Package Rbenv from the following Git repo at the given commit hash or
  ## tag.
  ##
  ## NOTE: if you change one of these, but the Rbenv version number hasn't
  ## changed since the last fullstaq-rbenv package release, then be sure to
  ## bump `package_revision`!
  repo: https://github.com/fullstaq-labs/fullstaq-rbenv.git
  ref: fbaa15993171bf

  ## Or package Rbenv from the following local directory.
  ## Be sure to comment out 'repo' and 'ref' if you use this.
  # path: /path-to-your-local-fork

  ## (Required)
  ## Specify the rbenv version number without commit hash
  ## suffix. Find it out with:
  ##
  ##   bin/rbenv --version | awk '{ print $2 }' | sed -E 's/(.+)-.*/\1/'
  ##
  ## NOTE: if you change `version`, be sure to reset
  ## `package_revision` to 0.
  version: 1.1.2-16

  ## (Required)
  ## Package revision number.
  package_revision: 1

## (Required)
## fullstaq-ruby-common package parameters.
##
## NOTE: if you change `version`, be sure to reset
## `package_revision` to 0.
common:
  rpm:
    version: 1.0
    package_revision: 0
  deb:
    version: 1.0
    package_revision: 0

## (Required)
## Which variants to build.
variants:
  normal: true
  jemalloc: true
  malloctrim: true

## (Required if variants.jemalloc is true)
## Version of Jemalloc to compile against.
##
## NOTE: If you change this, then be sure to bump the Ruby
## `package_revision` numbers too!
jemalloc_version: 3.6.0

## (Required)
## Specify which distributions to build packages for.
## When set to 'all', will build for all supported distributions.
distributions: all
## You can also set it to a list of distribution names.
## The names must match the folder names found in the environments/
## directory in this project.
# distributions:
#   - centos-7
#   - centos-8
#   - debian-9
#   - debian-10
#   - debian-11
#   - ubuntu-18.04
#   - ubuntu-20.04
